// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_up9Ws3HkSLdxQ1lAj4ga1qOYBtLFZs',
    appId: '1:211459354538:web:578c51733dc7b940bcc5d3',
    messagingSenderId: '211459354538',
    projectId: 'communal-ar',
    authDomain: 'communal-ar.firebaseapp.com',
    storageBucket: 'communal-ar.firebasestorage.app',
    measurementId: 'G-QQT6YXX0KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6h0uWvTZVGw3kb_uTVx-Ww5ccvjhdNPs',
    appId: '1:211459354538:android:5ca9bcecf07a1de1bcc5d3',
    messagingSenderId: '211459354538',
    projectId: 'communal-ar',
    storageBucket: 'communal-ar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyG5bXLFdAvTc8sudv9u8pcYhr7aTPNJE',
    appId: '1:211459354538:ios:125ad4aa73d1466bbcc5d3',
    messagingSenderId: '211459354538',
    projectId: 'communal-ar',
    storageBucket: 'communal-ar.firebasestorage.app',
    iosBundleId: 'com.example.communal',
  );
}
