import 'package:get/get.dart';

class LocalizationText extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'community-list-no-items':
              'You are not a member of any communities.\n\nYou can create your own or request an invite from the admins of other communities.',
          'community-books-no-items': 'No books found in this community.',
          'community-members-no-items':
              'No members found in this community.\n\nThis is likely an internet error or a bug with the app.',
          'community-topics-no-items': 'No topics have been created in this community.',
        },
        'es_ES': {
          'Login': 'Ingresar',
          'Register': 'Registrarse',
          'Sign in': 'Iniciar sesión',
          'Create account': 'Crear cuenta',
          'Forgot password?': '¿Olvidaste tu contraseña?',
          'Resend confirmation?': '¿Reenviar confirmación?',
          'Resend confirmation': 'Reenviar confirmación',
          'Reset password': 'Reestablecer contraseña',
          'Recover password': 'Recuperar contraseña',
          'Name': 'Nombre',
          'Username': 'Usuario',
          'Send': 'Enviar',
          'Email': 'Email',
          'Password': 'Contraseña',
          'Search': 'Buscar',
          'Status': 'Estado',
          'Edit': 'Editar',
          'Delete': 'Borrar',
          'Information': 'Información',
          'Reviews': 'Reseñas',
          'Owner': 'Dueño',
          'View loan': 'Ver préstamo',
          'No reviews': 'Sin reseñas',
          'Added': 'Agregado',
          'Loaned': 'Prestado',
          'Borrowed': 'Recibido',
          'Requested': 'Solicitado',
          'Request': 'Solicitar',
          'Withdraw request': 'Retirar solicitud',
          'Available': 'Disponible',
          'Unavailable': 'No Disponible',
          'Profile': 'Perfil',
          'Messages': 'Mensajes',
          'Users': 'Usuarios',
          'My Books': 'Mis Libros',
          'Communities': 'Comunidades',
          'Invitations': 'Invitaciones',
          'Invite user': 'Invitar usuario',
          'Invite': 'Invitar',
          'Loans': 'Prestamos',
          'Dark': 'Oscuro',
          'Notifications': 'Notificaciones',
          'Light': 'Claro',
          'Save': 'Guardar',
          'About me': 'Sobre mí',
          'Edit profile': 'Editar perfil',
          'Make email public?': '¿Hacer email público?',
          'Logout': 'Salir',
          'Please enter something': 'Por favor ingresar algo',
          'Delete account': 'Eliminar cuenta',
          'Sign in with Google': 'Entrar con Google',
          'Bio (Optional)': 'Bio (Opcional)',
          'Description (Optional)': 'Descripción (Opcional)',
          'Add\nimage': 'Agregar\nimagen',
          'Create community': 'Crear comunidad',
          'member': 'miembro',
          'Books': 'Libros',
          'Discuss': 'Conversar',
          'Members': 'Miembros',
          'Create': 'Crear',
          'Create topic': 'Crear conversación',
          'you': 'tú',
          'Settings': 'Configuración',
          'Remove admin': 'Quitar admin',
          'Make admin': 'Hacer admin',
          'Kick': 'Echar',
          'Undo': 'Deshacer',
          'community-list-no-items':
              'Aún no te uniste a ninguna comunidad.\n\nPodes crear una propia o solicitar una invitación a comunidades existentes.',
          'community-books-no-items': 'No se encontraron libros en esta comunidad.',
          'community-members-no-items':
              'No se encontraron usuarios en esta comunidad.\nEsto es probablemente un error de conexión o un bug.',
          'community-topics-no-items': 'No se crearon conversaciones en esta comunidad.',
        },
      };
}
