import 'package:get/get.dart';

class LocalizationText extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'community-list-no-items':
              'You are not a member of any communities.\n\nYou can create your own or request an invite from the admins of other communities.',
          'community-books-no-items': 'No books found in this community.',
          'community-members-no-items':
              'No members found in this community.\n\nThis is likely an internet error or a bug with the app.',
          'community-topics-no-items':
              'No topics have been created in this community.',
          'landing-shelf':
              'Add the books you own to your shelf. Your friends can see what\'s on it, and you can see what\'s on theirs.',
          'landing-community':
              'The people you\'ve added as friends, and the people they\'ve added. Nobody past that can see your books.',
          'landing-borrowing':
              'Ask the owner if you can borrow a book. If they say yes, message each other to meet up, and give it back when you\'re done.',
        },
        'es_ES': {
          'Login': 'Ingresar',
          'Language': 'Idioma',
          'Theme': 'Tema',
          'Register': 'Registrarse',
          'Sign in': 'Iniciar sesión',
          'Create account': 'Crear cuenta',
          'Forgot password?': '¿Olvidaste tu contraseña?',
          'Resend confirmation?': '¿Reenviar confirmación?',
          'Resend confirmation': 'Reenviar confirmación',
          'Reset password': 'Reestablecer contraseña',
          'Recover password': 'Recuperar contraseña',
          'Name': 'Nombre',
          'Username': 'Usuario',
          'Visibility': 'Visibilidad',
          'Public': 'Público',
          'Private': 'Privado',
          'Send': 'Enviar',
          'Email': 'Email',
          'Password': 'Contraseña',
          'Search': 'Buscar',
          'Status': 'Estado',
          'Edit': 'Editar',
          'Delete': 'Borrar',
          'Information': 'Información',
          'Reviews': 'Reseñas',
          'Owner': 'Dueño',
          'View loan': 'Ver préstamo',
          'No reviews': 'Sin reseñas',
          'Added': 'Agregado',
          'Loaned': 'Prestado',
          'Borrowed': 'Recibido',
          'Requested': 'Solicitado',
          'Request': 'Solicitar',
          'Withdraw request': 'Retirar solicitud',
          'Available': 'Disponible',
          'Unavailable': 'No Disponible',
          'Profile': 'Perfil',
          'My Profile': 'Mi Perfil',
          'Edit profile': 'Editar perfil',
          'Add friend': 'Agregar amigo',
          'Friends': 'Amigos',
          'Messages': 'Mensajes',
          'Users': 'Usuarios',
          'My Books': 'Mis Libros',
          'Communities': 'Comunidades',
          'Invitations': 'Invitaciones',
          'Invite user': 'Invitar usuario',
          'Invite': 'Invitar',
          'Loans': 'Prestamos',
          'Loan': 'Prestamo',
          'Dark': 'Oscuro',
          'Notifications': 'Notificaciones',
          'Light': 'Claro',
          'Save': 'Guardar',
          'About me': 'Sobre mí',
          'Show email?': '¿Mostrar email?',
          'Publicly visible?': '¿Públicamente visible?',
          'Logout': 'Salir',
          'Please enter something': 'Por favor ingresar algo',
          'Input must be a valid email.': 'Ingresá un email válido.',
          'Username is already taken.': 'El usuario ya está en uso.',
          'Username must be at least 6 characters long':
              'El usuario debe tener al menos 6 caracteres',
          'Username must be at most 20 characters long':
              'El usuario debe tener como máximo 20 caracteres',
          'Username should only include ASCII characters':
              'El usuario solo puede incluir caracteres ASCII',
          'Bio must be at least 20 characters long':
              'La bio debe tener al menos 20 caracteres',
          'Bio must be at most 1000 characters long':
              'La bio debe tener como máximo 1000 caracteres',
          'Must be at least {n} characters long.':
              'Debe tener al menos {n} caracteres.',
          'Checking username...': 'Verificando usuario...',
          'Delete account': 'Eliminar cuenta',
          'Enter with Google': 'Entrar con Google',
          'Bio (Optional)': 'Bio (Opcional)',
          'Description (Optional)': 'Descripción (Opcional)',
          'Add\nimage': 'Agregar\nimagen',
          'Create community': 'Crear comunidad',
          'member': 'miembro',
          'Books': 'Libros',
          'Discuss': 'Conversar',
          'Members': 'Miembros',
          'Create': 'Crear',
          'Add': 'Agregar',
          'Create topic': 'Crear conversación',
          'On loan': 'En préstamo',
          'Home': 'Inicio',
          'See all': 'Ver todos',
          'Recent reviews from friends': 'Reseñas recientes de tus amigos',
          'New in your network': 'Nuevo en tu red',
          'Reviews by friends': 'Reseñas de amigos',
          "Owner's note": 'Nota del dueño',
          'Review': 'Reseña',
          'Wants to borrow this book': 'Quiere este libro prestado',
          'Owner · you asked to borrow this book':
              'Dueño · le pediste este libro',
          'Is borrowing this book': 'Tiene este libro prestado',
          'Borrowed this book': 'Tuvo este libro prestado',
          'Asked to borrow this book': 'Pidió este libro prestado',
          "Owner · you're borrowing this book":
              'Dueño · tenés este libro prestado',
          'Owner · you borrowed this book':
              'Dueño · tuviste este libro prestado',
          'No books from your friends yet.\nFind people you know in Search.':
              'Todavía no hay libros de tus amigos.\nBuscá gente que conozcas en Buscar.',
          'Your friends have not reviewed any books yet.':
              'Tus amigos todavía no reseñaron ningún libro.',
          'Loan rejected': 'Préstamo rechazado',
          'Loan completed': 'Prestamo completado',
          'Returned': 'Devuelto',
          'Rejected': 'Rechazado',
          'Approved': 'Aceptado',
          'All': 'Todos',
          'Date': 'Fecha',
          'Title': 'Título',
          'Pending': 'Pendiente',
          'Accepted': 'Aceptado',
          'Completed': 'Completado',
          'you': 'tú',
          'Settings': 'Configuración',
          'Remove admin': 'Quitar admin',
          'Make admin': 'Hacer admin',
          'Kick': 'Echar',
          'Undo': 'Deshacer',
          'Order by': 'Ordenar por',
          'Loanee': 'Solicitante',
          'Filter by status': 'Filtrar por estado',
          'Filter by book ownership': 'Filtrar por propiedad',
          'Filter by': 'Filtrar por',
          'Mark as returned': 'Marcar como devuelto',
          'Approve': 'Aceptar',
          'Reject': 'Rechazar',
          'Own': 'Propio',
          'Foreign': 'Ajeno',
          'Review by': 'Reseña por',
          'Review (Optional)': 'Reseña (Opcional)',
          'Write a review...': 'Escribir una reseña...',
          'Author': 'Autor',
          'Submit': 'Enviar',
          'Cancel': 'Cancelar',
          'Your review': 'Tu reseña',
          'Edit review': 'Editar reseña',
          'Request status': 'Estado de la solicitud',
          'Your request for ': 'Tu solicitud por ',
          'A request has been submitted for ': 'Ingresó una solicitud por ',
          'Your loan for ': 'Tu préstamo de ',
          'You have been invited to join the community ':
              'Fuiste invitado a unirte a la comunidad ',
          'You have joined the community ': 'Te uniste a la comunidad ',
          ' has been accepted by ': ' fue aceptada por ',
          ' has been rejected by ': ' fue rechazada por ',
          ' by ': ' de parte de ',
          ' has been marked as returned by ': ' fue marcado como devuelto por ',
          'Type something...': 'Ecribe algo...',
          'Seen': 'Visto',
          'Chat messages in Communal are still unencrypted, please refrain from sharing sensitive information here':
              'Los chats en Communal aún no están encriptados, por favor evitar compatir información sensible aquí',
          'No books found in your library.': 'No tenés libros en tu biblioteca.',
          'community-list-no-items':
              'Aún no te uniste a ninguna comunidad.\n\nPodes crear una propia o solicitar una invitación a comunidades existentes.',
          'community-books-no-items':
              'No se encontraron libros en esta comunidad.',
          'community-members-no-items':
              'No se encontraron usuarios en esta comunidad.\nEsto es probablemente un error de conexión o un bug.',
          'community-topics-no-items':
              'No se crearon conversaciones en esta comunidad.',
          'Requests': 'Solicitudes',
          'Sent': 'Enviadas',
          'Remove': 'Eliminar',
          'Withdraw': 'Retirar',
          'Accept': 'Aceptar',
          'Message': 'Mensaje',
          'Accept this request?': '¿Aceptar esta solicitud?',
          'Reject this request?': '¿Rechazar esta solicitud?',
          'Withdraw friend request?': '¿Retirar solicitud de amistad?',
          'Remove {name} as friend?': '¿Eliminar a {name} de tus amigos?',
          'No pending requests.': 'No hay solicitudes pendientes.',
          'Server error.': 'Error del servidor.',
          'You have no friends yet.': 'Todavía no tenés amigos.',
          'You have not sent any requests.': 'No enviaste ninguna solicitud.',
          'You requested this book from': 'Solicitaste este libro a',
          'requested this book': 'solicitó este libro',
          'Is friends with {name}': 'Es amigo/a de {name}',
          'and {n} more': 'y {n} más',
          'No books found among your friends and their friends.':
              'No se encontraron libros entre tus amigos y sus amigos.',
          'Notify me when available': 'Avisarme cuando esté disponible',
          'Stop notifying me': 'Dejar de avisarme',
          ' is available again.': ' está disponible de nuevo.',
          'Show my books to friends of friends':
              'Mostrar mis libros a amigos de amigos',
          'Preferences': 'Preferencias',
          'View profile': 'Ver perfil',
          'Book added': 'Libro agregado',
          'Changes saved': 'Cambios guardados',
          'Book deleted': 'Libro eliminado',
          'Profile saved': 'Perfil guardado',
          'Loan requested': 'Préstamo solicitado',
          'Loan approved': 'Préstamo aprobado',
          'Friend request sent': 'Solicitud de amistad enviada',
          'Try again': 'Reintentar',
          'Add book': 'Agregar libro',
          'No loans found.': 'No se encontraron préstamos.',
          'No messages yet.': 'Aún no hay mensajes.',
          'No notifications yet.': 'Aún no hay notificaciones.',
          'No users found.': 'No se encontraron usuarios.',
          'No books match "{query}"': 'No se encontraron libros para "{query}"',
          'No users match "{query}"': 'No se encontraron usuarios para "{query}"',
          'Delete chat': 'Borrar chat',
          'Delete chat?': '¿Borrar chat?',
          'New password': 'Nueva contraseña',
          'Repeat password': 'Repetir contraseña',
          'Change password': 'Cambiar contraseña',
          'Passwords do not match': 'Las contraseñas no coinciden',
          'Password updated.': 'Contraseña actualizada.',
          'Password must be at least 6 characters long':
              'La contraseña debe tener al menos 6 caracteres',
          'Password should only include ASCII characters':
              'La contraseña solo puede incluir caracteres ASCII',
          'Error in updating password, please try again.':
              'Error al actualizar la contraseña, intentá de nuevo.',
          'This deletes your profile, books, loans, messages and friendships. It cannot be undone.':
              'Esto borra tu perfil, libros, préstamos, mensajes y amistades. No se puede deshacer.',
          'Are you sure you want to delete your account? This is immediate and cannot be undone.':
              '¿Seguro que querés borrar tu cuenta? Es inmediato y no se puede deshacer.',
          'Could not delete your account, please try again.':
              'No se pudo borrar tu cuenta, intentá de nuevo.',
          'landing-shelf':
              'Agregá los libros que tenés a tu biblioteca. Tus amigos pueden ver qué hay en ella, y vos lo que hay en las suyas.',
          'landing-community':
              'Las personas que agregaste como amigos, y las que agregaron ellos. Más allá de eso, nadie ve tus libros.',
          'landing-borrowing':
              'Preguntale al dueño si te presta un libro. Si te dice que sí, arreglen por mensaje para verse, y devolvelo cuando lo termines.',
          'Add your books': 'Agregá tus libros',
          'Who\'s in your community': 'Quién está en tu comunidad',
          'How borrowing works': 'Cómo funcionan los préstamos',
          'You': 'Vos',
          'Friends of friends': 'Amigos de amigos',
          'Return': 'Devolver',
          'Skip': 'Saltear',
          'Next': 'Siguiente',
          'Get started': 'Empezar',
          'Ask the owner': 'Pedíselo al dueño',
          'Meet up': 'Júntense',
          'When you\'re done': 'Cuando lo termines',
        },
      };
}
