import 'package:get/get.dart';

class LocalizationText extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'community-list-no-items':
              'You are not a member of any communities.\n\nYou can create your own or request an invite from the admins of other communities.',
          'community-books-no-items': 'No books found in this community.',
          'community-members-no-items':
              'No members found in this community.\n\nThis is likely an internet error or a bug with the app.',
          'community-topics-no-items': 'No topics have been created in this community.',
          'landing-upload-books':
              'Snap photos of your physical books to add them to the app. Share your collection and let others discover what you love to read.',
          'landing-join-communities':
              'Find groups of friends, clubs, or local book lovers. Build shared libraries by collaborating with people you trust.',
          'landing-share-books':
              'Request books from your peers or lend out yours. Track loans and discuss reads with others.',
        },
        'es_ES': {
          'Login': 'Ingresar',
          'Register': 'Registrarse',
          'Sign in': 'Iniciar sesión',
          'Create account': 'Crear cuenta',
          'Forgot password?': '¿Olvidaste tu contraseña?',
          'Resend confirmation?': '¿Reenviar confirmación?',
          'Resend confirmation': 'Reenviar confirmación',
          'Reset password': 'Reestablecer contraseña',
          'Recover password': 'Recuperar contraseña',
          'Name': 'Nombre',
          'Username': 'Usuario',
          'Visibility': 'Visibilidad',
          'Public': 'Público',
          'Private': 'Privado',
          'Send': 'Enviar',
          'Email': 'Email',
          'Password': 'Contraseña',
          'Search': 'Buscar',
          'Status': 'Estado',
          'Edit': 'Editar',
          'Delete': 'Borrar',
          'Information': 'Información',
          'Reviews': 'Reseñas',
          'Owner': 'Dueño',
          'View loan': 'Ver préstamo',
          'No reviews': 'Sin reseñas',
          'Added': 'Agregado',
          'Loaned': 'Prestado',
          'Borrowed': 'Recibido',
          'Requested': 'Solicitado',
          'Request': 'Solicitar',
          'Withdraw request': 'Retirar solicitud',
          'Available': 'Disponible',
          'Unavailable': 'No Disponible',
          'Profile': 'Perfil',
          'Messages': 'Mensajes',
          'Users': 'Usuarios',
          'My Books': 'Mis Libros',
          'Communities': 'Comunidades',
          'Invitations': 'Invitaciones',
          'Invite user': 'Invitar usuario',
          'Invite': 'Invitar',
          'Loans': 'Prestamos',
          'Loan': 'Prestamo',
          'Dark': 'Oscuro',
          'Notifications': 'Notificaciones',
          'Light': 'Claro',
          'Save': 'Guardar',
          'About me': 'Sobre mí',
          'Edit profile': 'Editar perfil',
          'Make email public?': '¿Hacer email público?',
          'Publicly visible?': '¿Públicamente visible?',
          'Logout': 'Salir',
          'Please enter something': 'Por favor ingresar algo',
          'Delete account': 'Eliminar cuenta',
          'Sign in with Google': 'Entrar con Google',
          'Bio (Optional)': 'Bio (Opcional)',
          'Description (Optional)': 'Descripción (Opcional)',
          'Add\nimage': 'Agregar\nimagen',
          'Create community': 'Crear comunidad',
          'member': 'miembro',
          'Books': 'Libros',
          'Discuss': 'Conversar',
          'Members': 'Miembros',
          'Create': 'Crear',
          'Add': 'Agregar',
          'Create topic': 'Crear conversación',
          'Loan accepted': 'Prestamo aceptado',
          'Loan rejected': 'Prestamo rechazado',
          'Loan completed': 'Prestamo completado',
          'Returned': 'Devuelto',
          'Rejected': 'Rechazado',
          'Approved': 'Aceptado',
          'All': 'Todos',
          'Date': 'Fecha',
          'Title': 'Título',
          'Pending': 'Pendiente',
          'Accepted': 'Aceptado',
          'Completed': 'Completado',
          'you': 'tú',
          'Settings': 'Configuración',
          'Remove admin': 'Quitar admin',
          'Make admin': 'Hacer admin',
          'Kick': 'Echar',
          'Undo': 'Deshacer',
          'Order by': 'Ordenar por',
          'Loanee': 'Recipiente',
          'Filter by status': 'Filtrar por estado',
          'Filter by book ownership': 'Filtrar por propiedad',
          'Filter by': 'Filtrar por',
          'Mark as returned': 'Marcar como devuelto',
          'Approve': 'Aceptar',
          'Reject': 'Rechazar',
          'Own': 'Propio',
          'Foreign': 'Ajeno',
          'Review by': 'Reseña por',
          'Review (Optional)': 'Reseña (Opcional)',
          'Write a review...': 'Escribir una reseña...',
          'Author': 'Autor',
          'Submit': 'Enviar',
          'Cancel': 'Cancelar',
          'Your review': 'Tu reseña',
          'Edit review': 'Editar reseña',
          'Your request for ': 'Tu solicitud por ',
          'A request has been submitted for ': 'Ingresó una solicitud por ',
          'Your loan for ': 'Tu préstamo de ',
          'You have been invited to join the community ': 'Fuiste invitado a unirte a la comunidad ',
          'You have joined the community ': 'Te uniste a la comunidad ',
          ' has been accepted by ': ' fue aceptada por ',
          ' has been rejected by ': ' fue rechazada por ',
          ' by ': ' de parte de ',
          ' has been marked as returned by ': ' fue marcado como devuelto por ',
          'Type something...': 'Ecribe algo...',
          'Seen': 'Visto',
          'Upload your books': 'Subí tus libros',
          'Join communities': 'Unite a comunidades',
          'Share books': 'Compartí libros',
          'Chat messages in Communal are still unencrypted, please refrain from sharing sensitive information here':
              'Los chats en Communal aún no están encriptados, por favor evitar compatir información sensible aquí',
          'No books found in your library.\n\nYou can upload some with the floating button on the bottom right.':
              'No tienes libros en tu biblioteca.\n\nPuedes subir algunos usando el botón flotante abajo a la derecha.',
          'community-list-no-items':
              'Aún no te uniste a ninguna comunidad.\n\nPodes crear una propia o solicitar una invitación a comunidades existentes.',
          'community-books-no-items': 'No se encontraron libros en esta comunidad.',
          'community-members-no-items':
              'No se encontraron usuarios en esta comunidad.\nEsto es probablemente un error de conexión o un bug.',
          'community-topics-no-items': 'No se crearon conversaciones en esta comunidad.',
          'landing-upload-books':
              'Sacá fotos a tus libros físicos para subirlos a la app. Compartí tu colección y permití que otros descubran lo que te gusta leer.',
          'landing-join-communities':
              'Encuentra grupos de amigos, clubes o apasionados de los libros. Construí librerías compartidas junto a tu círculo de confianza.',
          'landing-share-books':
              'Solicitá libros de tus compañeros o prestá los tuyos. Seguí tus prestamos y charla sobre tus lecturas con otros.',
        },
      };
}
